server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: frontend
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        cachecontrol:
          no-cache: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: never
