server:
  port: ${SERVER_PORT}
  servlet:
    session:
      cookie:
        name: ${SESSION_COOKIE_NAME}
        http-only: true
        secure: ${SESSION_COOKIE_SECURE}
        same-site: lax

spring:
  application:
    name: frontend
  http:
    clients:
      connect-timeout: ${HTTP_CLIENT_CONNECT_TIMEOUT}
      read-timeout: ${HTTP_CLIENT_READ_TIMEOUT}
  data:
    redis:
      host: ${SESSION_REDIS_HOST}
      port: ${SESSION_REDIS_PORT}
      username: ${SESSION_REDIS_USERNAME}
      password: ${SESSION_REDIS_PASSWORD}
      connect-timeout: ${SESSION_REDIS_CONNECT_TIMEOUT}
      timeout: ${SESSION_REDIS_COMMAND_TIMEOUT}
      ssl:
        enabled: ${SESSION_REDIS_SSL_ENABLED}
  session:
    timeout: ${SESSION_TIMEOUT}
    data:
      redis:
        namespace: ${SESSION_REDIS_NAMESPACE}
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        cachecontrol:
          no-cache: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: never

clients:
  identity:
    base-url: ${IDENTITY_SERVICE_BASE_URL}
    username: ${FRONTEND_USERNAME}
    password: ${FRONTEND_PASSWORD}
